### ISSUE TITLE
segmentation fault on getcomputorlist

### ISSUE THREAD

**Issue by georgmittendorfer** [qubic-network/qubic-cli#1]
`qubic-cli -nodeip <ip-of-public-computor> -getcomputorlist`

returns the list of computors but ends with segmentation fault (compiled from source today - commit hash `3ca58d517c68fca591fc316225cef5ad40ccc395`). debian linux.

```
[...]
Epoch: 83
Computor list is VERIFIED (signed by ARBITRATOR)
Segmentation fault
```

**Comment by krypdkat** [comment]
> `qubic-cli -nodeip <ip-of-public-computor> -getcomputorlist`
> 
> returns the list of computors but ends with segmentation fault (compiled from source today - commit hash `3ca58d517c68fca591fc316225cef5ad40ccc395`). debian linux.
> 
> ```
> [...]
> Epoch: 83
> Computor list is VERIFIED (signed by ARBITRATOR)
> Segmentation fault
> ```

@georgmittendorfer  missing an output file `qubic-cli -nodeip <ip-of-public-computor> -getcomputorlist comp.bin`
